repositoryUrl: https://github.com/dynamsoft-docs/label-recognition-docs-js/blob/main
repository: Dynamsoft-docs/label-recognition-docs-js
docFullPath: https://www.dynamsoft.com/label-recognition/docs/web
firstLevelUrl: /label-recognition/docs/web
docRootName: "Label Recognizer JS Edition" 
docHomePage: /label-recognition/docs/web/programming/javascript/

parameters-reference: /label-recognition/docs/core/parameters/reference/

js: /label-recognition/docs/web/programming/javascript/
js-api: /label-recognition/docs/web/programming/javascript/api-reference/
js-release-notes: /label-recognition/docs/web/programming/javascript/release-notes/

assets: /label-recognition/docs/core/assets/
edit_icon: /label-recognition/docs/core/assets/img-icon/edit-icon.png
smile_icon: /label-recognition/docs/core/assets/img-icon/icon-smile.png
sad_icon: /label-recognition/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /label-recognition/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /label-recognition/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /label-recognition/docs/core/assets/img-icon/icon-dnt.svg

release-notes: /label-recognition/docs/core/release-notes/
license-activation: /label-recognition/docs/core/license-activation/

useVersionTree: true

baseurl: "/label-recognition/docs/web"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

